// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/app/dao/internal"
)

// dynastyDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type dynastyDao struct {
	*internal.DynastyDao
}

var (
	// Dynasty is globally public accessible object for table dynasty operations.
	Dynasty = dynastyDao{
		internal.NewDynastyDao(),
	}
)

// Fill with you ideas below.