// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/app/dao/internal"
)

// poemDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type poemDao struct {
	*internal.PoemDao
}

var (
	// Poem is globally public accessible object for table poem operations.
	Poem = poemDao{
		internal.NewPoemDao(),
	}
)

// Fill with you ideas below.