// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Poet is the golang structure of table poet for DAO operations like Where/Data.
type Poet struct {
	g.Meta    `orm:"table:poet, do:true"`
	Id        interface{} //
	Name      interface{} //
	Profile   interface{} //
	DynastyId interface{} //
}
