// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "poetry/internal/logic/dynasty"
	_ "poetry/internal/logic/poem"
	_ "poetry/internal/logic/poet"
)
