// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Dynasty is the golang structure of table dynasty for DAO operations like Where/Data.
type Dynasty struct {
	g.Meta `orm:"table:dynasty, do:true"`
	Id     interface{} //
	Name   interface{} //
}
