// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Poem is the golang structure of table poem for DAO operations like Where/Data.
type Poem struct {
	g.Meta  `orm:"table:poem, do:true"`
	Id      interface{} //
	Form    interface{} //
	Tags    interface{} //
	Name    interface{} //
	Content interface{} //
	PoetId  interface{} //
}
