// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta         `orm:"table:user, do:true"`
	Id             interface{} //
	FullName       interface{} //
	Email          interface{} //
	HashedPassword interface{} //
	IsActive       interface{} //
	IsSuperuser    interface{} //
}
