// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Dynasty is the golang structure for table dynasty.
type Dynasty struct {
	Id   string `json:"id"   ` //
	Name string `json:"name" ` //
}
