// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Poem is the golang structure for table poem.
type Poem struct {
	Id      string `json:"id"      ` //
	Form    string `json:"form"    ` //
	Tags    string `json:"tags"    ` //
	Name    string `json:"name"    ` //
	Content string `json:"content" ` //
	PoetId  string `json:"poetId"  ` //
}
