// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Poet is the golang structure for table poet.
type Poet struct {
	Id        string `json:"id"        ` //
	Name      string `json:"name"      ` //
	Profile   string `json:"profile"   ` //
	DynastyId string `json:"dynastyId" ` //
}
