// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"poetry/internal/model"
)

type IPoem interface {
	Today(ctx context.Context) (out *model.Poem, err error)
	GetBrief(ctx context.Context, in *model.PoemBriefInput) (out *model.PoemBriefOutput, err error)
	GetDetail(ctx context.Context, in *model.PoemDetailInput) (out *model.PoemDetailOutput, err error)
	Search(ctx context.Context, in *model.PoemSearchInput) (out *model.PoemSearchOutput, err error)
}

var localPoem IPoem

func Poem() IPoem {
	if localPoem == nil {
		panic("implement not found for interface IPoem, forgot register?")
	}
	return localPoem
}

func RegisterPoem(i IPoem) {
	localPoem = i
}
