// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"poetry/internal/model"
)

type IDynasty interface {
	GetList(ctx context.Context) (out *model.DynastyGetListOutput, err error)
}

var localDynasty IDynasty

func Dynasty() IDynasty {
	if localDynasty == nil {
		panic("implement not found for interface IDynasty, forgot register?")
	}
	return localDynasty
}

func RegisterDynasty(i IDynasty) {
	localDynasty = i
}
