// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"poetry/internal/dao/internal"
)

// internalDynastyDao is internal type for wrapping internal DAO implements.
type internalDynastyDao = *internal.DynastyDao

// dynastyDao is the data access object for table dynasty.
// You can define custom methods on it to extend its functionality as you wish.
type dynastyDao struct {
	internalDynastyDao
}

var (
	// Dynasty is globally public accessible object for table dynasty operations.
	Dynasty = dynastyDao{
		internal.NewDynastyDao(),
	}
)

// Fill with you ideas below.
