// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"poetry/internal/dao/internal"
)

// internalPoemDao is internal type for wrapping internal DAO implements.
type internalPoemDao = *internal.PoemDao

// poemDao is the data access object for table poem.
// You can define custom methods on it to extend its functionality as you wish.
type poemDao struct {
	internalPoemDao
}

var (
	// Poem is globally public accessible object for table poem operations.
	Poem = poemDao{
		internal.NewPoemDao(),
	}
)

// Fill with you ideas below.
